port                       = ""
bot_token                  = ""
verification_token         = ""
bot_id                     = ""
channel_id                 = ""
debug_channel_id           = ""
github_username            = ""
github_token               = ""
github_repository_owner    = ""
github_repository_name     = ""
github_commit_author_name  = ""
github_commit_author_email = ""
configuration_directory_path = ""
configuration_file_extension = ""
comma_separated_environments = ""
default_environment          = ""
